[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mycat"
version = "0.1.3"
description = "Desktop Cat: Qt Overlay"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "yumiaura" }]
classifiers = [
  "Environment :: X11 Applications :: Qt",
  "Intended Audience :: End Users/Desktop",
  "Programming Language :: Python :: 3",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS",
]
dependencies = [
  "PySide6>=6.5.0"
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]

# Console script `mycat` â†’ calls mycat.main:main
[project.scripts]
mycat = "mycat.main:main"

[tool.setuptools.packages.find]
include = ["mycat*"]

# Include packaged images inside the wheel
[tool.setuptools.package-data]
mycat = ["images/*"]

[tool.mypy]
strict = true

[tool.ruff]
line-length = 120
target-version = "py38"
extend-exclude = ["README.md", "docs/*"]

[tool.ruff.lint]
select = ["C4", "E", "F", "I", "PERF", "UP"]
ignore = ["PERF203"]
